# Session metadata
string subject_id
string notes

# Module configuration
string decider_module
bool decider_enabled
string preprocessor_module
bool preprocessor_enabled
string presenter_module
bool presenter_enabled

# Experiment configuration
string protocol_filename

# Data source info
string data_source

# Simulator parameters
string simulator_dataset_filename
float64 simulator_start_time

# Replay parameters
string replay_bag_id
bool replay_play_preprocessed