# Initialize pipeline component: decider

uint8[16] session_id

string project_name
string module_filename
bool enabled

# Pipeline info
bool preprocessor_enabled

# Stream info
eeg_interfaces/StreamInfo stream_info

# Metadata
string subject_id

# Safety configuration
float64 minimum_intertrial_interval
---
bool success
