# Used in the real-time pipeline for requesting timed trigger.
uint8[16] session_id
uint64 decision_id

TimedTrigger timed_trigger
float64 reference_sample_time  # seconds since recording start
---
bool success
