# Initialize pipeline component: preprocessor

uint8[16] session_id

string project_name
string module_filename
bool enabled

# Stream info
eeg_interfaces/StreamInfo stream_info

# Metadata
string subject_id
---
bool success
