#!/bin/bash

set -e

# Check that ROS is installed
if ! command -v ros2 &> /dev/null; then
    echo "ROS is not installed. Please install ROS before running this script."
    exit 1
fi

cd $NEUROSIMO_ROOT

# Build packages in src/interfaces directory
colcon build --base-paths src/interfaces
