#!/bin/bash

# Define the text formatting codes
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

echo "${BOLD}${UNDERLINE}Instructions for using NeuroSimo:${RESET}"
echo ""
echo "• Launch NeuroSimo app:   ${BOLD}neurosimo${RESET}"
echo ""
