#!/usr/bin/env python3
"""Generate a synthetic BrainVision recording for testing "Import recording" in the UI.

Output: three files sharing a base name (all three are needed):

    <name>.vhdr   header (this is what the UI lists)
    <name>.eeg    binary data (IEEE float32, multiplexed, little-endian)
    <name>.vmrk   markers (become the imported dataset's event file)

Where to put them
-----------------
Copy all three files into the active project's `external_recordings/` directory:

    $PROJECTS_ROOT/<project>/external_recordings/

On a standard install PROJECTS_ROOT is ~/projects (mounted as /app/projects inside
the containers), so for example:

    mkdir -p ~/projects/test/external_recordings
    cp test_recording.{vhdr,eeg,vmrk} ~/projects/test/external_recordings/

The project watcher only lists `.vhdr` files from that directory; it picks up new
files live. The importer (recording_importer) converts the recording into
`<project>/eeg_simulator/<name>.csv` + `<name>.json` (+ `<name>_events.csv` if
there are markers) and selects it as the simulator dataset.

Channel typing
--------------
MNE reads every BrainVision channel as EEG unless told otherwise. To get EMG
channels in the imported dataset, EEG channels are given electrode coordinates and
EMG channels are given zero coordinates, which makes MNE type them as 'misc'; the
importer then treats all non-EEG channels as EMG. (MNE emits a warning about this;
that is expected.)

Size
----
With the defaults (60 s, 5000 Hz, 63 EEG + 10 EMG) the .eeg file is ~88 MB and the
imported CSV is ~200 MB, so the import takes long enough to observe in the UI.

Usage
-----
    python3 scratch/generate_test_recording.py
    python3 scratch/generate_test_recording.py --duration 120 --name long_recording
    python3 scratch/generate_test_recording.py --output-dir ~/projects/test/external_recordings
"""

import argparse
import os

import numpy as np


def write_vhdr(path, name, sampling_frequency, num_eeg_channels, num_emg_channels):
    num_channels = num_eeg_channels + num_emg_channels
    sampling_interval_us = 1_000_000 // sampling_frequency

    lines = [
        'Brain Vision Data Exchange Header File Version 1.0',
        '; Generated by scratch/generate_test_recording.py',
        '',
        '[Common Infos]',
        'Codepage=UTF-8',
        f'DataFile={name}.eeg',
        f'MarkerFile={name}.vmrk',
        'DataFormat=BINARY',
        'DataOrientation=MULTIPLEXED',
        f'NumberOfChannels={num_channels}',
        '; Sampling interval in microseconds',
        f'SamplingInterval={sampling_interval_us}',
        '',
        '[Binary Infos]',
        'BinaryFormat=IEEE_FLOAT_32',
        '',
        '[Channel Infos]',
        '; Ch<n>=<name>,<reference>,<resolution>,<unit>',
    ]
    for i in range(num_eeg_channels):
        lines.append(f'Ch{i + 1}=EEG{i + 1},,1,µV')
    for i in range(num_emg_channels):
        lines.append(f'Ch{num_eeg_channels + i + 1}=EMG{i + 1},,1,µV')

    lines += [
        '',
        '[Coordinates]',
        '; Ch<n>=<radius>,<theta>,<phi>; zero coordinates mark non-EEG channels',
    ]
    for i in range(num_eeg_channels):
        theta = 20 + (i * 37) % 100
        phi = (i * 53) % 360
        lines.append(f'Ch{i + 1}=1,{theta},{phi}')
    for i in range(num_emg_channels):
        lines.append(f'Ch{num_eeg_channels + i + 1}=0,0,0')

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')


def write_vmrk(path, name, sampling_frequency, num_samples, event_interval):
    lines = [
        'Brain Vision Data Exchange Marker File Version 1.0',
        '',
        '[Common Infos]',
        'Codepage=UTF-8',
        f'DataFile={name}.eeg',
        '',
        '[Marker Infos]',
        '; Mk<n>=<type>,<description>,<position (1-based sample)>,<size>,<channel>',
    ]
    if event_interval > 0:
        step = int(round(event_interval * sampling_frequency))
        for index, sample in enumerate(range(step, num_samples, step)):
            lines.append(f'Mk{index + 1}=Stimulus,S  1,{sample + 1},1,0')

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')


def write_eeg(path, sampling_frequency, num_eeg_channels, num_emg_channels, num_samples, seed):
    """Write multiplexed float32 samples in µV, one second at a time."""
    rng = np.random.default_rng(seed)
    num_channels = num_eeg_channels + num_emg_channels

    # EEG: 10 Hz alpha (per-channel phase) + 6 Hz theta + white noise.
    eeg_phases = rng.uniform(0, 2 * np.pi, num_eeg_channels)
    # EMG: noise with a 1 s burst every 5 s.
    burst_period_s = 5.0
    burst_length_s = 1.0

    chunk_size = sampling_frequency
    with open(path, 'wb') as f:
        for start in range(0, num_samples, chunk_size):
            n = min(chunk_size, num_samples - start)
            t = (start + np.arange(n)) / sampling_frequency
            chunk = np.empty((n, num_channels), dtype='<f4')

            alpha = 20.0 * np.sin(2 * np.pi * 10.0 * t[:, None] + eeg_phases[None, :])
            theta = 8.0 * np.sin(2 * np.pi * 6.0 * t)[:, None]
            chunk[:, :num_eeg_channels] = alpha + theta + rng.normal(0, 5.0, (n, num_eeg_channels))

            if num_emg_channels > 0:
                in_burst = (t % burst_period_s) < burst_length_s
                amplitude = np.where(in_burst, 100.0, 5.0)[:, None]
                chunk[:, num_eeg_channels:] = amplitude * rng.normal(0, 1.0, (n, num_emg_channels))

            f.write(chunk.tobytes())


def main():
    parser = argparse.ArgumentParser(
        description='Generate a synthetic BrainVision recording (.vhdr/.eeg/.vmrk) for testing "Import recording".',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument('--name', default='test_recording', help='Base name of the output files')
    parser.add_argument('--output-dir', default='.', help='Directory to write the files to')
    parser.add_argument('--duration', type=float, default=60.0, help='Duration in seconds')
    parser.add_argument('--sampling-frequency', type=int, default=5000, help='Sampling frequency in Hz (must divide 1000000)')
    parser.add_argument('--eeg-channels', type=int, default=63, help='Number of EEG channels')
    parser.add_argument('--emg-channels', type=int, default=10, help='Number of EMG channels')
    parser.add_argument('--event-interval', type=float, default=2.0, help='Seconds between stimulus markers (0 = no markers)')
    parser.add_argument('--seed', type=int, default=0, help='Random seed')
    args = parser.parse_args()

    if args.sampling_frequency <= 0 or 1_000_000 % args.sampling_frequency != 0:
        parser.error('--sampling-frequency must be a positive divisor of 1000000 '
                     '(BrainVision stores the sampling interval in microseconds)')
    if args.eeg_channels < 1:
        parser.error('--eeg-channels must be at least 1')
    if args.emg_channels < 0:
        parser.error('--emg-channels must be non-negative')
    if args.duration <= 0:
        parser.error('--duration must be positive')

    output_dir = os.path.expanduser(args.output_dir)
    os.makedirs(output_dir, exist_ok=True)

    num_samples = int(round(args.duration * args.sampling_frequency))
    vhdr_path = os.path.join(output_dir, f'{args.name}.vhdr')
    vmrk_path = os.path.join(output_dir, f'{args.name}.vmrk')
    eeg_path = os.path.join(output_dir, f'{args.name}.eeg')

    # Write the header last so a watcher never sees a .vhdr without its data.
    write_eeg(eeg_path, args.sampling_frequency, args.eeg_channels, args.emg_channels, num_samples, args.seed)
    write_vmrk(vmrk_path, args.name, args.sampling_frequency, num_samples, args.event_interval)
    write_vhdr(vhdr_path, args.name, args.sampling_frequency, args.eeg_channels, args.emg_channels)

    size_mb = os.path.getsize(eeg_path) / 1e6
    print(f'Wrote {args.duration:g} s, {args.sampling_frequency} Hz, '
          f'{args.eeg_channels} EEG + {args.emg_channels} EMG channels ({size_mb:.1f} MB):')
    for path in (vhdr_path, eeg_path, vmrk_path):
        print(f'  {path}')
    print()
    print('Copy all three files to $PROJECTS_ROOT/<project>/external_recordings/ '
          '(typically ~/projects/<project>/external_recordings/).')


if __name__ == '__main__':
    main()
